# **Neural Networks From Scratch**

*demonstrates forward and backward propagation without using any external libraries like tensorflow or pytorch*

*in this example i have considered XOR gate to demonstrate how nural network can learn complex decision boundaries*

In [28]:
import numpy as np
x= np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y = np.array([
    [0],
    [1],
    [1],
    [0]])
y.shape,x.shape

((4, 1), (4, 2))

In [29]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [30]:
weights =2* np.random.random((2,1))-1
biase = 2* np.random.random(1)-1
out=x
output = sigmoid(np.dot(out,weights)+biase)
lr=0.1
weights,biase,output

(array([[-0.91533578],
        [-0.83724319]]),
 array([0.33744701]),
 array([[0.58357024],
        [0.37758857],
        [0.35941853],
        [0.19542587]]))

In [31]:
# gradient decent
for i in range(10000):
    first_term = output-y
    in_last_layer = np.dot(out,weights)+biase
    second_term = derivative_sigmoid(in_last_layer)
    first_two = first_term*second_term


    changes = np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * out[j][i]
    weights= weights-lr*changes

    bias_change=0.0
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]
    biase=biase-lr*bias_change
output=sigmoid(np.dot(x,weights)+biase)
weights,biase,output

(array([[6.09195651],
        [6.06293546]]),
 array([0.33744701]),
 array([[0.58357024],
        [0.99834183],
        [0.99838919],
        [0.99999624]]))

In [32]:
# gradient decent optimised

for i in range(10000):
    first_term = output-y
    in_last_layer = np.dot(out,weights)+biase
    second_term = derivative_sigmoid(in_last_layer)
    first_two = first_term*second_term


    changes = np.dot(out.T,first_two)

    bias_change= np.sum(first_two)
    biase=biase-lr*bias_change

output=sigmoid(np.dot(x,weights)+biase)
weights,biase,output

(array([[6.09195651],
        [6.06293546]]),
 array([-8.05954709]),
 array([[3.15970055e-04],
        [1.19559138e-01],
        [1.22647918e-01],
        [9.83622679e-01]]))

In [33]:
wh = 2* np.random.random((2,2))-1
bh = 2* np.random.random((1,2))-1

wo = 2* np.random.random((2,1))-1
bo = 2* np.random.random((1,1))-1

In [34]:
for i in range(1000):
    out=x
    input_hidden = np.dot(out,wh) + bh
    output_hidden = sigmoid(input_hidden)
    input_for_output_layer=np.dot(output_hidden,wo) + bo
    output = sigmoid(input_for_output_layer)

    first_term_output_layer=output-y
    second_term_output_layer= derivative_sigmoid(input_for_output_layer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivative_sigmoid(input_hidden)
    first_two_hidden_layer = first_term*second_term


    changes_output = np.dot(output_hidden.T,first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer,axis=0 ,keepdims=True)

    changes_hidden = np.dot(out.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis=0 ,keepdims=True)

    wo = wo - lr* changes_output
    bo = bo - lr* changes_output_bias

    wh = wo - lr* changes_output
    bh = bh - lr* changes_hidden_bias

out=x
input_hidden = np.dot(out,wh) + bh
output_hidden = sigmoid(input_hidden)
input_for_output_layer=np.dot(output_hidden,wo) + bo
output = sigmoid(input_for_output_layer)

output,wh,bh,wo,bo

(array([[0.49083329],
        [0.49215771],
        [0.50406203],
        [0.5061351 ]]),
 array([[0.63029107],
        [0.07806677]]),
 array([[-2.20515255, -1.80873207]]),
 array([[0.63034491],
        [0.07812467]]),
 array([[-0.11025637]]))